import Head from 'next/head'
import Hero from '../components/Home/Hero'
import HomeWork from '../components/Home/HomeWork'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Finsweet</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/logo.svg"/>
      </Head>
      <Hero heading="Building stellar websites for early startups" text="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt." buttonMain="View our work" buttonSm="View Pricing" img="Home/hero__main.svg" link="/work"/>
      <HomeWork/>
    </div>
  )
}
